name: Build and Export Artifact

on:
  workflow_dispatch:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Git
      run: |
        sudo apt update
        sudo apt install -y git

    - name: Install Node.js
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y nodejs npm
        sudo npm config set registry https://registry.npmmirror.com
        sudo npm install -g n
        sudo apt remove nodejs npm -y
        sudo apt autoremove -y
        sudo n latest

    - name: Install pnpm
      run: sudo npm install -g pnpm

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: SkySight-666/any-listen
        ref: dev
        path: any-listen

    - name: Build project
      working-directory: any-listen
      run: |
        pnpm install
        pnpm run build:web

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: any-listen/build
